no change     /gpfs/research/software/python/anaconda311/condabin/conda
no change     /gpfs/research/software/python/anaconda311/bin/conda
no change     /gpfs/research/software/python/anaconda311/bin/conda-env
no change     /gpfs/research/software/python/anaconda311/bin/activate
no change     /gpfs/research/software/python/anaconda311/bin/deactivate
no change     /gpfs/research/software/python/anaconda311/etc/profile.d/conda.sh
no change     /gpfs/research/software/python/anaconda311/etc/fish/conf.d/conda.fish
no change     /gpfs/research/software/python/anaconda311/shell/condabin/Conda.psm1
no change     /gpfs/research/software/python/anaconda311/shell/condabin/conda-hook.ps1
no change     /gpfs/research/software/python/anaconda311/lib/python3.11/site-packages/xontrib/conda.xsh
no change     /gpfs/research/software/python/anaconda311/etc/profile.d/conda.csh
no change     /gpfs/home/gdb20/.bashrc
No action taken.
Lmod has detected the following error: Cannot load module "python/3" because
these module(s) are loaded:
   anaconda

While processing the following module(s):
    Module fullname  Module Filename
    ---------------  ---------------
    python/3         /opt/modulefiles/core/python/3.lua

Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
normal termination of xtb
